# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "user": "local"
}

### get repository
GET {{host}}/api/repositories/{{repo}}
Cookie: {{login.response.headers.Set-Cookie}}

### missing repository
GET {{host}}/api/repositories/missing
Cookie: {{login.response.headers.Set-Cookie}}

### unauthenticated
GET {{host}}/api/repositories/{{repo}}
Cookie: lirox_session=invalid
