use actix_web::web;

pub(crate) fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(crate::index)
        .service(crate::login)
        .service(crate::save_login)
        .service(crate::logout)
        .service(crate::install)
        .service(crate::save_install)
        .service(crate::onboarding)
        .service(crate::save_onboarding)
        .service(crate::workspace_page)
        .service(crate::note_page)
        .service(crate::auth_root_api)
        .service(crate::auth_login_api)
        .service(crate::auth_logout_api)
        .service(crate::auth_api)
        .service(crate::install_api)
        .service(crate::workspaces_api)
        .service(crate::create_workspace_api)
        .service(crate::workspace_resource_api)
        .service(crate::sync_workspace_api)
        .service(crate::get_workspace_file_api)
        .service(crate::put_workspace_file_api)
        .service(crate::delete_workspace_file_api)
        .service(crate::conflicts_api)
        .service(crate::trash_api)
        .service(crate::repositories_api)
        .service(crate::repository_api)
        .service(crate::connect_repository_api)
        .service(crate::disconnect_repository_api)
        .service(crate::save_note)
        .service(crate::notes_preflight)
        .service(crate::workspace_api)
        .service(crate::workspace_preflight)
        .service(crate::api_preflight);
}
