[package]
name = "liroxnotes-app"
edition.workspace = true
version.workspace = true

[[bin]]
name = "liroxnotes-app"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
dioxus = { workspace = true, features = ["web"] }
liroxnotes-shared = { path = "../shared" }
js-sys = "0.3.82"
wasm-bindgen = "0.2.103"
web-sys = { version = "0.3.82", features = ["Window", "Location", "History", "PopStateEvent", "CustomEvent", "Event", "EventTarget"] }
