[package]
name = "liroxnotes-app"
version = "0.1.0"
authors = ["Yoram <yoramdelangen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus.workspace = true
liroxnotes-shared = { path = "../shared" }

[features]
default = ["web"]
web = ["dioxus/web"]
