# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "user": "local"
}

### get workspace
GET {{host}}/api/workspaces/{{workspace}}
Cookie: {{login.response.headers.Set-Cookie}}

### missing workspace
GET {{host}}/api/workspaces/missing
Cookie: {{login.response.headers.Set-Cookie}}

### unauthenticated
GET {{host}}/api/workspaces/{{workspace}}
Cookie: lirox_session=invalid
